### ISSUE TITLE
there was a problem in restoring the data

### ISSUE THREAD

**Issue by tengzhuofei** [bitnami/bitnami-docker-mongodb-sharded#10]
mongodb bitnami/mongodb-sharded:4.4.1-debian-10-r60

I backed up the data by hard linking the data directory of the master node of the configuration and data pod and copying the files, and then there was a problem in restoring the data.

using the same replica set keys

[mongod-2-0.log](https://github.com/bitnami/bitnami-docker-mongodb-sharded/files/5872150/mongod-2-0.log)
[mongod-2-1.log](https://github.com/bitnami/bitnami-docker-mongodb-sharded/files/5872152/mongod-2-1.log)

Using mongod --repair still cannot fix the problem

[mongodb.log](https://github.com/bitnami/bitnami-docker-mongodb-sharded/files/5872153/mongodb.log)

**Comment by dani8art** [comment]
Hi @tengzhuofei,

could you provide the way you set up the cluster? and the step you did to restore the data?

Thanks!

**Comment by tengzhuofei** [comment]
config

# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false

# where to write logging data.
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0

# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
  #bindIp:

# replica set options
replication:
  replSetName: mongodb-sharded-shard-0
  enableMajorityReadConcern: true

# sharding options
sharding:
  clusterRole: shardsvr

# process management options
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

# set parameter options
setParameter:
   enableLocalhostAuthBypass: false

# security options
security:
  authorization: enabled
  keyFile: /opt/bitnami/mongodb/conf/keyfile

**Comment by tengzhuofei** [comment]
use https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded

[mongodb.zip](https://github.com/bitnami/bitnami-docker-mongodb-sharded/files/5877348/mongodb.zip)

**Comment by dani8art** [comment]
> use https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded

This is the way you set up the cluster, right?

We would also need the way you restored the data, please.
- how did you build this `zip`? 
- when you say "copying the files" do you mean extract this `zip` inside a new release of mongodb-sharded? or what did you do? 
- Are you copying the entire `/bitnami/mongodb-sharded`?
- did you use the same secrets between both charts releases? this is important since the chart generates secrets randomly and they will be unsync between storage and env vars.

**Comment by tengzhuofei** [comment]
I copy the entire /bitnami/mongodb-sharded with per a pod，using the same replica set keys

**Comment by dani8art** [comment]
You need to use the same mongodb root password as well and if you are setting mongodb user then use the same mongodb user password.  

BTW, please, could you provide the exact steps to replicate your environment? we would like to reproduce the issue in our local environment.

**Comment by tengzhuofei** [comment]
I use https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded,and running 3 configsvr,2 mongos,3 shard and 2 replicaset and 1 arbiter.
I backed up the data by hard linking the data directory of the master node of the configuration and data pod and copying the files, and then there was a problem in restoring the data.
because my secondary has journaling enabled and its journal and data files are on the same volume,so I am not top all write operations.But I stop balance.
the uncompressed size of the data is 170Gi.I copy the entire /bitnami/mongodb-sharded with per a pod，using the same replica set keys in new cluster.

**Comment by andresbono** [comment]
Hi @tengzhuofei, we are still unable to reproduce the scenario. In any case, checking the logs, it seems like your backup is corrupted and it couldn't be restored.

Maybe you were copying the files while MongoDB was running. See what the official documentation says:

https://docs.mongodb.com/manual/core/backups/#back-up-with-cp-or-rsync
> [...] you can copy the files directly using cp, rsync, or a similar tool. Since copying multiple files is not an atomic operation, you must stop all writes to the mongod before copying the files. Otherwise, you will copy the files in an invalid state.
