### ISSUE TITLE
Install MongoDB Sharded in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-mongodb-sharded#12]
## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/107856962-a9eb8180-6df9-11eb-9c30-5445940a56a4.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/107856969-b40d8000-6df9-11eb-933b-ff67a80cb8d1.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements as the following ones are selected as default for the tutorial,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/107856977-bc65bb00-6df9-11eb-8198-9c495da49b54.PNG)

* Select the number of workers in Worker Pool. In our case, we'll set it to three (3) as Mongodb-sharded requires it. 
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint.

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/107856999-c12a6f00-6df9-11eb-9b11-ea6077ac4287.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/107857003-c5ef2300-6df9-11eb-8cf9-ec116019aa12.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/107857008-cc7d9a80-6df9-11eb-8d60-d8337ecbcebd.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/107857017-d1424e80-6df9-11eb-8561-3ea6a4cd30ce.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/107857026-dc957a00-6df9-11eb-8035-9d8d3d6804fd.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/107857028-e0290100-6df9-11eb-93d5-224ff6fddd48.PNG)

## Step 3: Verify Installation of Cloud Block Storage plug-in and configuration

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/107857030-e4edb500-6df9-11eb-8358-3e680b7386f4.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/107857035-ea4aff80-6df9-11eb-9674-fcb67515ea1e.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/107857038-ef0fb380-6df9-11eb-8ecb-ced35b66cd0a.PNG)

![test7](https://user-images.githubusercontent.com/70336951/107857040-f20aa400-6df9-11eb-9ac9-85ff7561ffcf.PNG)

* Once you have installed the terminal, open it, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *storage-example* is now active.

`$ kubectl get ns`

![teststorage6](https://user-images.githubusercontent.com/70336951/107857044-f8008500-6df9-11eb-9bac-01e5597b7081.PNG)

* To install MongoDB it is necessary to check that our storage class is in the block storage gold class by default. To verify that the storage class is in default we use the following command. Also, you can follow IBM tutorial on how to change the default class storage [here](https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/ "here"). 

`$ kubectl get storageclass`

![teststorage1](https://user-images.githubusercontent.com/70336951/107857059-10709f80-6dfa-11eb-929d-87874ab454db.PNG)

* In our example, the storage class is by default in IBM-file-gold, we will change that to the IBM-block-gold to make mongodb-sharded work. To do this, we first remove the IBM-file-gold as the default class storage by following this command:

`$ kubectl patch storageclass ibm-file-gold -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'`

![teststorage2](https://user-images.githubusercontent.com/70336951/107857057-0c448200-6dfa-11eb-89cc-eeb2a8ab4749.PNG)

* Check the change is correctly applied. 

`$ kubectl get storageclass`

![teststorage3](https://user-images.githubusercontent.com/70336951/107857063-1a929e00-6dfa-11eb-9219-51308988a058.PNG)

* Now, mark the IBM-block-gold storage as default by inputting the following command.

`$ kubectl patch storageclass ibmc-block-gold -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'`

![teststorage4](https://user-images.githubusercontent.com/70336951/107857067-1fefe880-6dfa-11eb-90a7-d892346fcfa7.PNG)

`$ kubectl get storageclass`

![teststorage5](https://user-images.githubusercontent.com/70336951/107857072-241c0600-6dfa-11eb-8235-c6df4d40e79d.PNG)

## Step 4: Install MongoDB Sharded

* Click on the search section at the top of the main page, type Redis, and click on _MongoDB(R) Sharded packaged by Bitnami_.

![mongo1](https://user-images.githubusercontent.com/70336951/107857076-2d0cd780-6dfa-11eb-9420-03a92a9b5721.PNG)

* A new window opens, select the cluster and enter the name you want for the Redis workspace or select an exist workspace, in this case, we'll create a new one and it will be called _mongodb-sharded_, accept the terms and click on *Install*. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/mongodb-sharded-Qml0bmFtaS1tb25nb2RiLXNoYXJkZWQ=-global#about "here").

![mongo2](https://user-images.githubusercontent.com/70336951/107857083-35fda900-6dfa-11eb-8d59-f37d48928bbf.PNG)

* You can modify the different installation parameters at the bottom. We will leave them by default except for the root password, which you will need to access your MongoDB console and work with your databases.

Make sure you set up a password in the _mongodbRootPassword_ variable. 

![mongo3](https://user-images.githubusercontent.com/70336951/107857085-3a29c680-6dfa-11eb-871b-996300a23ce3.PNG)

## Step 4: Verify Installation MongoDB Sharded

* Open the web terminal and type the following command. You can see *mongodb-sharded* is now active.

`$ kubectl get ns`

![testmongo1](https://user-images.githubusercontent.com/70336951/107857088-40b83e00-6dfa-11eb-8552-3d8c3eb02213.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testmongo2](https://user-images.githubusercontent.com/70336951/107857089-457cf200-6dfa-11eb-9b47-9a5fac945c43.PNG)

`$ kubectl get service -n NAME SERVICE`

![testmongo3](https://user-images.githubusercontent.com/70336951/107857092-4b72d300-6dfa-11eb-882b-e0210c8c6b02.PNG)

* Select the master pod within your service using bash.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

* Check if MongoDB Sharded is correctly installed by checking the server version or using any of the MongoDB commands.

` mongod --version `

![testmongo4](https://user-images.githubusercontent.com/70336951/107857100-54fc3b00-6dfa-11eb-841b-da6654711420.PNG)

` mongod --h `

![testmongo5](https://user-images.githubusercontent.com/70336951/107857104-59285880-6dfa-11eb-9859-e93e5c07908d.PNG)

You have finished the installation, enjoy your MongoDB Sharded installation!

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
