### ISSUE TITLE
support for Secret file using swarm 

### ISSUE THREAD

**Issue by traderpedroso** [bitnami/bitnami-docker-mongodb-sharded#14]
as the default config for compose using as string would like to use secrets on docker swarm Secret file

**Comment by traderpedroso** [comment]
> as the default config for compose using as string would like to use secrets on docker swarm Secret file

sorry i found it out on the script

# 3. Environment variables overridden via external files using *_FILE variables (see below)

**Comment by traderpedroso** [comment]
the solution works on Docker Swarm Secrets file using Portainer 


``yml
version: '3.7'

secrets:
    mongo-root-password:
      external: true
    mongo-key:
      external: true
  

services:
  mongodb-sharded:
    image: docker.io/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg-primary
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
    ports:
      - "27017:27017"
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-sharded-2:
    image: docker.io/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded-2
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg-primary
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-shard0-primary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - 'shard0_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-shard0-secondary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    depends_on:
      - mongodb-shard0-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-shard0-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - 'shard0_sec_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-shard1-primary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard1-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_REPLICA_SET_NAME=shard1
    volumes:
      - 'shard1_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-shard1-secondary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    depends_on:
      - mongodb-shard1-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard1-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-shard1-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_REPLICA_SET_NAME=shard1
    volumes:
      - 'shard1_sec_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-shard2-primary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard2-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_REPLICA_SET_NAME=shard2
    volumes:
      - 'shard2_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-shard2-secondary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    depends_on:
      - mongodb-shard2-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard2-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-shard2-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_REPLICA_SET_NAME=shard2
    volumes:
      - 'shard2_sec_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-cfg-primary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg-primary
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - 'cfg_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

  mongodb-cfg-secondary:
    image: docker.io/bitnami/mongodb-sharded:4.4
    depends_on:
      - mongodb-cfg-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-cfg-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-password
      - MONGODB_REPLICA_SET_KEY_FILE=/run/secrets/mongo-key
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_SHARDING_MODE=configsvr
    volumes:
      - 'cfg_sec_data:/bitnami'
    secrets:
      - mongo-key
      - mongo-root-password

volumes:
  shard0_data:
    driver: local
  shard0_sec_data:
    driver: local
  shard1_data:
    driver: local
  shard1_sec_data:
    driver: local
  shard2_data:
    driver: local
  shard2_sec_data:
    driver: local
  cfg_data:
    driver: local
  cfg_sec_data:
    driver: local
``

**Comment by alvneiayu** [comment]
hi @traderpedroso 

Thanks for sharing your solution. It will be really helpful for the community.

Thanks a lot again

Álvaro
