### ISSUE TITLE
Persisting the database to specified folder

### ISSUE THREAD

**Issue by 1OGAG** [bitnami/bitnami-docker-mongodb-sharded#19]
**Description**
Database persistence, as mentioned in the Read.me, does not persist to the specified directory: instead it writes to /var/lib/docker/volumes/desktop_shard_0_data/_data.  

**Steps to reproduce the issue:**

1. run `curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-mongodb-sharded/master/docker-compose.yml > docker-compose.yml`
2. create a directory and change the permissions: chmod 1001:1001 
- `mkdir /home/user/Desktop/mongo && chmod 1001:1001 /home/user/Desktop/mongo`
3. Modify the compose file by adding
>  volumes: <br> - /home/user/Desktop/mongo:/bitnami
4. `docker-compose up -d`

**Describe the results you received:**

Subfolders within the specified persistence folder are created. I see "mongodb" and within it "data." The data directory has no files within it. Inspecting the volumes of the shard, you see

running docker volume ls

```DRIVER    VOLUME NAME
local     desktop_cfg_data
local     desktop_shard0_data
```
running docker inspect desktop_shard0_data

``` [
    {
        "CreatedAt": "2021-08-16T11:15:06-04:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "desktop",
            "com.docker.compose.version": "1.29.2",
            "com.docker.compose.volume": "shard0_data"
        },
        "Mountpoint": "/var/lib/docker/volumes/desktop_shard0_data/_data",
        "Name": "desktop_shard0_data",
        "Options": null,
        "Scope": "local"
    }
]
```
**Describe the results you expected:**

I'm not very skilled at docker but the files, I believe, are being stored in the docker virtual filesystem since this path doesn't exist on the host. And persistence works so the mongo data files are being stored. Is there a way to persist data to the folder that was mapped in the docker-compose.yml?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-27-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.842GiB
 Name: vbox
 ID: YR3R:HEVN:VJWT:45MH:J276:JQPL:CW3X:C3D6:ZXZM:LMRC:SR6P:W3M6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VirtualBox Version 6.1.26 r145957 (Qt5.6.2)

**Comment by pablogalegoc** [comment]
Hi @1OGAG!

I created the `shard0_data` and `cfg_data` directories and these are the changes I made to the `docker-compose.yml` make it work with bind mounts:
 ```diff
-      - 'shard0_data:/bitnami'
+     - ./shard0_data:/bitnami

-      - 'cfg_data:/bitnami'
+     - ./cfg_data:/bitnami

- volumes:
-   shard0_data:
-     driver: local
-   cfg_data:
-     driver: local
```

**Comment by 1OGAG** [comment]
Thanks for the quick response @pablogalegoc 

This does create the folders for me, however both the cfg and shard containers will exit due to the following error:
```mkdir: cannot create directory '/bitnami/mongodb': Permission denied```
Could you confirm that all three containers stay up and running without errors?

Thanks for the assist.

**Comment by pablogalegoc** [comment]
Ah sorry, forgot to mention to change the permissions on those folders. In case you’ve tried and the problem persists could you `ls -l` on them and paste the output?
> Could you confirm that all three containers stay up and running without errors?

Can confirm, yes:
```
❯ docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS              PORTS                                           NAMES
4c9dbf39caa0   bitnami/mongodb-sharded:4.4   “/opt/bitnami/script…”   2 minutes ago   Up About a minute   0.0.0.0:27017->27017/tcp, :::27017->27017/tcp   tests_mongodb-sharded_1
16eeb2209940   bitnami/mongodb-sharded:4.4   “/opt/bitnami/script…”   2 minutes ago   Up About a minute   27017/tcp                                       tests_mongodb-shard0_1
f83c2a497bed   bitnami/mongodb-sharded:4.4   “/opt/bitnami/script…”   2 minutes ago   Up About a minute   27017/tcp                                       tests_mongodb-cfg_1
```

**Comment by 1OGAG** [comment]
Yup, changing the permissions worked. I was letting the directories be created by docker but once I created the directory myself and changed the permissions it worked fine. For anyone else that has this problem in the future this worked for me:

1. Modify the docker-compose as indicated by @pablogalegoc 
2. create the directories
3. chown 1001:1001 on both directories
4. chmod 770 on both directories

If you leave Docker to create the folders you'll get them set with 1001:docker but this doesn't work. 
Thanks for the help! Not sure if this info would be worthwhile to put in the readme.

**Comment by pablogalegoc** [comment]
If you think it is you are very welcome to open a PR! In some other non-root containers there's a [notice](https://github.com/bitnami/bitnami-docker-wordpress#mount-host-directories-as-data-volumes-with-docker-compose) like 
> NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.

**Comment by 1OGAG** [comment]
Done. Thanks again for the help.
