### ISSUE TITLE
[Helm] user and database not created

### ISSUE THREAD

**Issue by quantm241** [bitnami/bitnami-docker-mongodb-sharded#2]
**Description**

**Steps to reproduce the issue:**

1. Install mongodb-sharded via helm chart
2. Connect to database via mongos
3. Show database and user

**Describe the results you received:**

Database and user was not created

**Describe the results you expected:**

Database and custom user will be create after mongo running up

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
Hi, thanks for filling this issue. Please, can you provide more info to reproduce the issue?

- The command used to install the chart. Did you modify the default _values.yaml_ or provide parameters using `--set`?
- What command are you using to connect mongo and what query are you doing?

Thanks!

**Comment by quantm241** [comment]
I install the chart using `helm install --name mongodb-sharded bitnami/mongodb-sharded`
The values set to values.yaml
- mongodbUsername: dbuser
- mongodbDatabase: mydatabase

After the helm chart installed successful, I access to a mongos pod with `kubectl exec ...` then try to login with username `dbuser` and password get from secret but get authentication failed.
So I try to use `root` user to login -> success.
In mongo shell I type `show dbs` -> It show admin and config db, not `mydatabase`
When I try query user from admin db -> only have root user, It not create dbuser

**Comment by carrodher** [comment]
Hi,
I was checking the code and this feature was not migrated from the MongoDB chart to the Sharded one, so although the values exist the logic to use those values is not implemented.

I already created an internal task to fix this issue, but I can't provide you an estimation, it depends on other priorities; anyway, PRs are welcome.

Thanks for reporting this issue.
