### ISSUE TITLE
Upgrade to MongoDB enterprise

### ISSUE THREAD

**Issue by F43RY** [bitnami/bitnami-docker-mongodb-sharded#23]
Hi everyone,
first of all thx for your great work!!!
What should I do if I would upgrade my deployment to enterprise version of mongoDB?

Thx

**Comment by alemorcuq** [comment]
According to the official documentation (https://docs.mongodb.com/manual/tutorial/upgrade-to-enterprise-sharded-cluster/), you just need to upgrade your nodes one by one. 

We don't have a MongoDB Enterprise image, so you would need to create one yourself. I suggest asking in the community forums for more detailed info: https://docs.mongodb.com/manual/tutorial/upgrade-to-enterprise-sharded-cluster/
