### ISSUE TITLE
How to run MongoDB cluster with mongo-express Web interface?

### ISSUE THREAD

**Issue by Oleg26Dev** [bitnami/bitnami-docker-mongodb-sharded#27]
How to add mongo-express to these docker-compose files like it is done here?

https://gist.github.com/adamelliotfields/cd49f056deab05250876286d7657dc4b

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by Oleg26Dev** [comment]
Thank you @carrodher , but in any case in my opinion it is useful to have a Docker + MongoDB cluster+Mongo-express as a Web inteface

**Comment by carrodher** [comment]
Thanks for the suggestion, I agree it can be useful in certain use cases but for us, it is difficult to have images/configurations for all the scenarios. We're a small team maintaining a lot of containers and Helm charts so we try to do our images as open and customizable as possible so users can modify them to meet different requirements.

You can create a _docker-compose.yaml_ with this container image plus any other third party image to make it work
