### ISSUE TITLE
mongos is not started

### ISSUE THREAD

**Issue by pluksha** [bitnami/bitnami-docker-mongodb-sharded#30]
### Name and Version

4.4.13-debian-10-r11

### What steps will reproduce the bug?

1. deploy the helm chart (https://charts.bitnami.com/bitnami/mongodb-sharded version 3.1.0) with 2 shards and 1 replica for each shard via terraform
2. deploy the new release helm chart ( (https://charts.bitnami.com/bitnami/mongodb-sharded version 3.1.0)) with 2 shards and 3 replica for each shard via terraform

### What is the expected behavior?

1. deploy the helm chart (https://charts.bitnami.com/bitnami/mongodb-sharded version 3.1.0) with 2 shards and 1 replica for each shard via terraform
2. deploy the new release helm chart ( (https://charts.bitnami.com/bitnami/mongodb-sharded version 3.1.0)) with 2 shards and 3 replica for each shard via terraform
3. mongos is not started with error:

### What do you see instead?

1. deploy the helm chart (https://charts.bitnami.com/bitnami/mongodb-sharded version 3.1.0) with 2 shards and 1 replica for each shard via terraform
2. deploy the new release helm chart ( (https://charts.bitnami.com/bitnami/mongodb-sharded version 3.1.0)) with 2 shards and 3 replica for each shard via terraform
3. mongos is not started with error:
`Liveness probe failed: MongoDB shell version v4.4.13 connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused : connect@src/mongo/shell/mongo.js:374:17 @(connect):2:6 exception: connect failed exiting with code 1`
Go inside the container and check - looks like it is the infinitive loop:
`mongodb 11:38:45.98
mongodb 11:38:45.98 Welcome to the Bitnami mongodb-sharded container
mongodb 11:38:45.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb 11:38:45.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb 11:38:45.98
mongodb 11:38:45.98 INFO ==> ** Starting MongoDB Sharded setup **
mongodb 11:38:46.12 INFO ==> Validating settings in MONGODB_* env vars...
mongodb 11:38:46.14 INFO ==> Initializing Mongos...
mongodb 11:38:46.14 INFO ==> Writing keyfile for replica set authentication...
mongodb 11:38:46.18 INFO ==> Trying to connect to MongoDB server mongodb-mongodb-sharded-configsvr-0.mongodb-mongodb-sharded-headless.mongodb-test.svc.cluster.local...
mongodb 11:38:46.19 INFO ==> Found MongoDB server listening at mongodb-mongodb-sharded-configsvr-0.mongodb-mongodb-sharded-headless.mongodb-test.svc.cluster.local:27017 !
mongodb 11:41:16.06
mongodb 11:41:16.06 Welcome to the Bitnami mongodb-sharded container
mongodb 11:41:16.06 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb 11:41:16.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb 11:41:16.07
mongodb 11:41:16.07 INFO ==> ** Starting MongoDB Sharded setup **
mongodb 11:41:16.13 INFO ==> Validating settings in MONGODB_* env vars...
mongodb 11:41:16.14 INFO ==> Initializing Mongos...
mongodb 11:41:16.14 INFO ==> Writing keyfile for replica set authentication...
mongodb 11:41:16.17 INFO ==> Trying to connect to MongoDB server mongodb-mongodb-sharded-configsvr-0.mongodb-mongodb-sharded-headless.mongodb-test.svc.cluster.local...
mongodb 11:41:16.18 INFO ==> Found MongoDB server listening at mongodb-mongodb-sharded-configsvr-0.mongodb-mongodb-sharded-headless.mongodb-test.svc.cluster.local:27017 !`

### Additional information

`
I have no name!@mongodb-mongodb-sharded-mongos-8449957f68-lhjx5:/$ ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001       329  0.0  0.0   2388   764 pts/0    Ss   11:43   0:00 sh -c clear; (bash || ash || sh)
1001       335  0.0  0.0   2388    92 pts/0    S    11:43   0:00  \_ sh -c clear; (bash || ash || sh)
1001       336  0.0  0.0   3868  3268 pts/0    S    11:43   0:00      \_ bash
1001       337  0.0  0.0   7640  2852 pts/0    R+   11:43   0:00          \_ ps auxf
1001         1  0.0  0.0   4936  4276 ?        Ss   11:41   0:00 /bin/bash /opt/bitnami/scripts/mongodb-sharded/entrypoint.sh /opt/bitnami/scripts/mongodb-sharded/run.sh
1001        14  0.0  0.0   5000  4196 ?        S    11:41   0:00 /bin/bash /opt/bitnami/scripts/mongodb-sharded/setup.sh
1001       328  0.0  0.0   2296   756 ?        S    11:43   0:00  \_ sleep 5
`

**Comment by javsalgar** [comment]
Hi,

Regarding this

```
deploy the new release helm chart ( (https://charts.bitnami.com/bitnami/mongodb-sharded version 3.1.0)) with 2 shards and 3 replica for each shard via terraform

```

Is this a `helm upgrade` command?
