### ISSUE TITLE
Update ReadMe about "Upgrade" in Chart bitnami/mongodb-sharded

### ISSUE THREAD

**Issue by SmallJeff** [bitnami/bitnami-docker-mongodb-sharded#31]
### Name and Version

bitnami/mongodb-sharded: shard version: 4.4.11-debian-10-r6

### What is the problem this feature will solve?

Add new shard to shard cluster on EKS but failed. 

For shard instances created from scratch, the collection **system.version** in **admin** db
{"featureCompatibilityVersion","version" :"4.4" }

For shard instances created from upgrade, the collection **system.version** in **admin** db
{"featureCompatibilityVersion","version" :"4.2" }

At last, the latter instance block at "Joining the cluster" because of "Auth Failed".

### What is the feature you are proposing to solve the problem?

Add --set image.tag param to helm upgrade command, like this

> helm upgrade RELEASE bitnami/mongodb-sharded --set image.tag=4.4.11-debian-10-r6

### What alternatives have you considered?

Fix bugs in .sh files in docker image.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
