### ISSUE TITLE
Support of mongodb 4.4.x

### ISSUE THREAD

**Issue by achupryn** [bitnami/bitnami-docker-mongodb-sharded#5]
Will be great to have images for mongodb 4.4.x. Thanks

**Comment by rafariossaa** [comment]
Hi,
  Thanks for you interest, we are currently working on releasing mongodb 4.4.x in our catalog. 
  It should be released in the next weeks, so stay tuned.

**Comment by rafariossaa** [comment]
I am closing this issue.
