### ISSUE TITLE
MONGODB_PRIMARY_ROOT_USER: unbound variable

### ISSUE THREAD

**Issue by lwj5** [bitnami/bitnami-docker-mongodb-sharded#6]
**Description**
This happened on a cluster installed with helm chart and it only affects this particular shard.
Does anyone have any idea how to resolve it?

Other shards seem to be running fine.

**Steps to reproduce the issue:**

1. Scale down shard to 0
2. Scale back up

**Describe the results you received:**

```
06:51:07.67 INFO  ==> Setting node as primary
mongodb 06:51:07.71 
mongodb 06:51:07.71 Welcome to the Bitnami mongodb-sharded container
mongodb 06:51:07.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb 06:51:07.72 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb 06:51:07.72 
mongodb 06:51:07.72 INFO  ==> ** Starting MongoDB Sharded setup **
mongodb 06:51:07.75 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 06:51:07.78 INFO  ==> Initializing MongoDB Sharded...
mongodb 06:51:07.85 INFO  ==> Writing keyfile for replica set authentication...
mongodb 06:51:07.88 INFO  ==> Enabling authentication...
mongodb 06:51:07.90 INFO  ==> Deploying MongoDB Sharded with persisted data...
mongodb 06:51:07.93 INFO  ==> Trying to connect to MongoDB server mongodb-sharded...
mongodb 06:51:07.95 INFO  ==> Found MongoDB server listening at mongodb-sharded:27017 !
mongodb 06:51:08.12 INFO  ==> MongoDB server listening and working at mongodb-sharded:27017 !
/opt/bitnami/scripts/libmongodb-sharded.sh: line 31: MONGODB_PRIMARY_ROOT_USER: unbound variable
```

**Describe the results you expected:**

Shard to start up normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
19.3.12
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 199
  Running: 164
  Paused: 0
  Stopped: 35
 Images: 85
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.19.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 251.6GiB
 Name: hidden
 ID: hidden
 Docker Root Dir: /mnt/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
-
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
physical

**Comment by andresbono** [comment]
Hi @lwj5, thanks for opening this issue. Could you please let us know how did you deploy the chart? Did you use the default values?

**Comment by lwj5** [comment]
@andresbono I upgraded the chart to the latest 2.1.1. It shows up on all primary shard. The pods start normally though so I'm just ignoring it.

> 12:19:48.72 INFO  ==> Setting node as primary
> mongodb 12:19:48.76 
> mongodb 12:19:48.76 Welcome to the Bitnami mongodb-sharded container
> mongodb 12:19:48.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
> mongodb 12:19:48.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
> mongodb 12:19:48.78 
> mongodb 12:19:48.78 INFO  ==> ** Starting MongoDB Sharded setup **
> mongodb 12:19:48.82 INFO  ==> Validating settings in MONGODB_* env vars...
> mongodb 12:19:48.86 INFO  ==> Initializing MongoDB Sharded...
> mongodb 12:19:48.92 INFO  ==> Writing keyfile for replica set authentication...
> mongodb 12:19:48.96 INFO  ==> Enabling authentication...
> mongodb 12:19:48.98 INFO  ==> Deploying MongoDB Sharded with persisted data...
> mongodb 12:19:49.02 INFO  ==> Trying to connect to MongoDB server mongodb-sharded...
> mongodb 12:19:49.04 INFO  ==> Found MongoDB server listening at mongodb-sharded:27017 !
> mongodb 12:19:49.22 INFO  ==> MongoDB server listening and working at mongodb-sharded:27017 !
> /opt/bitnami/scripts/libmongodb-sharded.sh: line 31: MONGODB_PRIMARY_ROOT_USER: unbound variable
> mongodb 12:20:40.62 INFO  ==> Joining the shard cluster
> mongodb 12:20:40.79 INFO  ==> Stopping MongoDB...
> mongodb 12:21:05.90 INFO  ==> ** MongoDB Sharded setup finished! **
> mongodb 12:21:05.94 INFO  ==> ** Starting MongoDB **
> {"t":{"$date":"2020-09-14T12:21:05.994+00:00"},"s":"W",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****","tags":["startupWarnings"]}
> {"t":{"$date":"2020-09-14T12:21:05.994+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
> {"t":{"$date":"2020-09-14T12:21:05.999+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}

**Comment by andresbono** [comment]
Hi @lwj5, we have been checking the issue in more depth and it seems this is caused by this aliasing:

https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/d87bbe490101bc09e63bac674e4e5071833f7734/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh#L123-L124

We will update the container image scripts so that the error message is not thrown. In any case, as you mention, the container bootstrap  is not affected by this.

**Comment by lwj5** [comment]
Thanks, @andresbono for checking! Feel free to close the issue if you do not need it for tracking.

**Comment by andresbono** [comment]
Hi @lwj5, the latest images already include the fix to the bug that you found: https://github.com/bitnami/bitnami-docker-mongodb-sharded/commit/c15e396920da70f14023ef802c81624b14052b41. Thanks for reporting it!
